---
title: Meerdere zelfgemaakte schakelaars of knoppen bedraden
hero_image: images/banner.png
description: Hoe kan je meerdere zelfgemaakte schakelaars of knoppen aansluiten op je Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-09"
steps:
  - title: Meerdere zelfgemaakte schakelaars of knoppen bedraden
