title: Wire multiple crafted switches or buttons
hero_image: images/banner.png
description: How to wire multiple craft switches or buttons to your Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-09"
steps:
  - 
    title: Wire multiple crafted switches or buttons
