title: Câbler plusieurs interrupteurs ou boutons artisanaux
hero_image: images/banner.png
description: Comment câbler plusieurs commutateurs ou boutons artisanaux à ton Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-09"
steps:
  - 
    title: Câbler plusieurs interrupteurs ou boutons artisanaux
